services:
  mongodb:
    image: mongo:8.0
    container_name: tomini-pos-mongodb
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: tomini_pos

    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongodb-keyfile"
      ]

    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/mongodb-keyfile:/etc/mongodb-keyfile:ro

volumes:
  mongodb_data: